require("config.remap")
require("config.lazy")
require("config.set")
require("config.commands")
require("config.aprenia")
require("config.godot")
require("config.holistic")
require("config.edit-code-block")

vim.diagnostic.config({ source = true, update_in_insert = true })
