#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    session=$1
else
    session=$(find ~ ~/.local ~/.config ~/.local/share ~/Downloads ~/workspace/ ~/workspace/aprenia/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $session ]]; then
    exit 0
fi

session_name=$(echo "$session" | tr ./ _)

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then 
    tmux new-session -s "$session_name" -c "$session" 
fi

if ! tmux has-session -t "$session_name" 2> /dev/null; then 
    if [[ -z $TMUX ]]; then
        tmux new-session -A -s "$session_name" -c "$session" 
        exit 1
    else
        tmux new-session -ds "$session_name" -c "$session" 
    fi
else
    if [[ -z $TMUX ]]; then
        tmux attach -t "$session_name"
        exit 1
    fi
fi

tmux switch-client -t "$session_name"
